//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_BuffArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Buff1Args")]
  public partial class Buff1Args : global::ProtoBuf.IExtensible
  {
    public Buff1Args() {}
    

    private int _Effect = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Effect
    {
      get { return _Effect; }
      set { _Effect = value; }
    }

    private int _Data = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Buff2Args")]
  public partial class Buff2Args : global::ProtoBuf.IExtensible
  {
    public Buff2Args() {}
    

    private int _Range = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Range
    {
      get { return _Range; }
      set { _Range = value; }
    }

    private int _Effect = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Effect
    {
      get { return _Effect; }
      set { _Effect = value; }
    }

    private int _Data = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Data
    {
      get { return _Data; }
      set { _Data = value; }
    }

    private int _Round = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Round
    {
      get { return _Round; }
      set { _Round = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}