//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_ChatArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
// Note: requires additional types generated from: protos/_BuffArgs.proto
// Note: requires additional types generated from: protos/_EquipArgs.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatArgs")]
  public partial class ChatArgs : global::ProtoBuf.IExtensible
  {
    public ChatArgs() {}
    

    private string _Player = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Player
    {
      get { return _Player; }
      set { _Player = value; }
    }

    private string _Content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShowEquipArgs")]
  public partial class ShowEquipArgs : global::ProtoBuf.IExtensible
  {
    public ShowEquipArgs() {}
    

    private string _Sender = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Sender", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Sender
    {
      get { return _Sender; }
      set { _Sender = value; }
    }

    private Action.Model.EquipArgs _Data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.EquipArgs Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodEquipArgs")]
  public partial class GoodEquipArgs : global::ProtoBuf.IExtensible
  {
    public GoodEquipArgs() {}
    

    private string _Player = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Player
    {
      get { return _Player; }
      set { _Player = value; }
    }

    private Action.Model.EquipArgs _Equip = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Equip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.EquipArgs Equip
    {
      get { return _Equip; }
      set { _Equip = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoodSoulArgs")]
  public partial class GoodSoulArgs : global::ProtoBuf.IExtensible
  {
    public GoodSoulArgs() {}
    

    private string _Player = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Player
    {
      get { return _Player; }
      set { _Player = value; }
    }

    private int _SoulId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SoulId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoulId
    {
      get { return _SoulId; }
      set { _SoulId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrivateChatArgs")]
  public partial class PrivateChatArgs : global::ProtoBuf.IExtensible
  {
    public PrivateChatArgs() {}
    

    private string _SendPlayer = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SendPlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string SendPlayer
    {
      get { return _SendPlayer; }
      set { _SendPlayer = value; }
    }

    private string _ReceivePlayer = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ReceivePlayer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ReceivePlayer
    {
      get { return _ReceivePlayer; }
      set { _ReceivePlayer = value; }
    }

    private string _Content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}