//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_EquipArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
// Note: requires additional types generated from: protos/CommonArgs.proto
// Note: requires additional types generated from: protos/_BuffArgs.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipArgs")]
  public partial class EquipArgs : global::ProtoBuf.IExtensible
  {
    public EquipArgs() {}
    

    private Action.Model.ObjArgs _Obj = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.ObjArgs Obj
    {
      get { return _Obj; }
      set { _Obj = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private Action.Model.Buff1Args _BasicBuff = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"BasicBuff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.Buff1Args BasicBuff
    {
      get { return _BasicBuff; }
      set { _BasicBuff = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.Buff1Args> _PluginBuffs = new global::System.Collections.Generic.List<Action.Model.Buff1Args>();
    [global::ProtoBuf.ProtoMember(5, Name=@"PluginBuffs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.Buff1Args> PluginBuffs
    {
      get { return _PluginBuffs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Equip2Args")]
  public partial class Equip2Args : global::ProtoBuf.IExtensible
  {
    public Equip2Args() {}
    

    private Action.Model.ObjArgs _Obj = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.ObjArgs Obj
    {
      get { return _Obj; }
      set { _Obj = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroEquipArgs")]
  public partial class HeroEquipArgs : global::ProtoBuf.IExtensible
  {
    public HeroEquipArgs() {}
    

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }

    private int _EquipId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"EquipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipId
    {
      get { return _EquipId; }
      set { _EquipId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WearEquipArgs")]
  public partial class WearEquipArgs : global::ProtoBuf.IExtensible
  {
    public WearEquipArgs() {}
    

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }

    private int _EquipId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"EquipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipId
    {
      get { return _EquipId; }
      set { _EquipId = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StrengthenEquipArgs")]
  public partial class StrengthenEquipArgs : global::ProtoBuf.IExtensible
  {
    public StrengthenEquipArgs() {}
    

    private int _EquipId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"EquipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipId
    {
      get { return _EquipId; }
      set { _EquipId = value; }
    }

    private int _EquipLevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"EquipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipLevel
    {
      get { return _EquipLevel; }
      set { _EquipLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompoundEquipArgs")]
  public partial class CompoundEquipArgs : global::ProtoBuf.IExtensible
  {
    public CompoundEquipArgs() {}
    

    private int _EquipId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"EquipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipId
    {
      get { return _EquipId; }
      set { _EquipId = value; }
    }

    private int _TargetId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TargetId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TargetId
    {
      get { return _TargetId; }
      set { _TargetId = value; }
    }

    private int _CompoundLucky = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CompoundLucky", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CompoundLucky
    {
      get { return _CompoundLucky; }
      set { _CompoundLucky = value; }
    }

    private bool _Flag = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompoundExpectArgs")]
  public partial class CompoundExpectArgs : global::ProtoBuf.IExtensible
  {
    public CompoundExpectArgs() {}
    

    private int _EquipId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"EquipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int EquipId
    {
      get { return _EquipId; }
      set { _EquipId = value; }
    }

    private int _CompoundLucky = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"CompoundLucky", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CompoundLucky
    {
      get { return _CompoundLucky; }
      set { _CompoundLucky = value; }
    }

    private int _TargetLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TargetLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TargetLevel
    {
      get { return _TargetLevel; }
      set { _TargetLevel = value; }
    }

    private int _Effect = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Effect
    {
      get { return _Effect; }
      set { _Effect = value; }
    }

    private int _Data = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}