//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_FriendArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadFriendsArgs")]
  public partial class LoadFriendsArgs : global::ProtoBuf.IExtensible
  {
    public LoadFriendsArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.FriendArgs> _FriendList = new global::System.Collections.Generic.List<Action.Model.FriendArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"FriendList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.FriendArgs> FriendList
    {
      get { return _FriendList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FriendArgs")]
  public partial class FriendArgs : global::ProtoBuf.IExtensible
  {
    public FriendArgs() {}
    

    private string _FriName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FriName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string FriName
    {
      get { return _FriName; }
      set { _FriName = value; }
    }

    private int _Sex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private bool _IfOnline = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"IfOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfOnline
    {
      get { return _IfOnline; }
      set { _IfOnline = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DelFriendArgs")]
  public partial class DelFriendArgs : global::ProtoBuf.IExtensible
  {
    public DelFriendArgs() {}
    

    private int _FriOrBlack = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"FriOrBlack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FriOrBlack
    {
      get { return _FriOrBlack; }
      set { _FriOrBlack = value; }
    }

    private string _friName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string friName
    {
      get { return _friName; }
      set { _friName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}