//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_GuildArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildArgs")]
  public partial class GuildArgs : global::ProtoBuf.IExtensible
  {
    public GuildArgs() {}
    

    private string _LeaderName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"LeaderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LeaderName
    {
      get { return _LeaderName; }
      set { _LeaderName = value; }
    }

    private string _GuildName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"GuildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GuildName
    {
      get { return _GuildName; }
      set { _GuildName = value; }
    }

    private string _Notice = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Notice
    {
      get { return _Notice; }
      set { _Notice = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _GuildExp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GuildExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GuildExp
    {
      get { return _GuildExp; }
      set { _GuildExp = value; }
    }

    private int _MemberMaxCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MemberMaxCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MemberMaxCount
    {
      get { return _MemberMaxCount; }
      set { _MemberMaxCount = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.GuildMemberArgs> _Members = new global::System.Collections.Generic.List<Action.Model.GuildMemberArgs>();
    [global::ProtoBuf.ProtoMember(7, Name=@"Members", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.GuildMemberArgs> Members
    {
      get { return _Members; }
    }
  

    private int _GuildRank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"GuildRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GuildRank
    {
      get { return _GuildRank; }
      set { _GuildRank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildMemberArgs")]
  public partial class GuildMemberArgs : global::ProtoBuf.IExtensible
  {
    public GuildMemberArgs() {}
    

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _TotalContribution = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TotalContribution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TotalContribution
    {
      get { return _TotalContribution; }
      set { _TotalContribution = value; }
    }

    private int _TodayContribution = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TodayContribution", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TodayContribution
    {
      get { return _TodayContribution; }
      set { _TodayContribution = value; }
    }

    private Action.Model.PostType _Post = Action.Model.PostType.Common;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Post", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.PostType.Common)]
    public Action.Model.PostType Post
    {
      get { return _Post; }
      set { _Post = value; }
    }

    private bool _IfOnline = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"IfOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfOnline
    {
      get { return _IfOnline; }
      set { _IfOnline = value; }
    }

    private int _MemberVip = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MemberVip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MemberVip
    {
      get { return _MemberVip; }
      set { _MemberVip = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _ArenaRank = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"ArenaRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ArenaRank
    {
      get { return _ArenaRank; }
      set { _ArenaRank = value; }
    }

    private int _Sex = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AskForGuildsArgs")]
  public partial class AskForGuildsArgs : global::ProtoBuf.IExtensible
  {
    public AskForGuildsArgs() {}
    

    private int _Page = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Page
    {
      get { return _Page; }
      set { _Page = value; }
    }

    private bool _GuildIsFull = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"GuildIsFull", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool GuildIsFull
    {
      get { return _GuildIsFull; }
      set { _GuildIsFull = value; }
    }

    private string _GuildName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"GuildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GuildName
    {
      get { return _GuildName; }
      set { _GuildName = value; }
    }

    private string _GuildLeader = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GuildLeader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GuildLeader
    {
      get { return _GuildLeader; }
      set { _GuildLeader = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadGuildsArgs")]
  public partial class LoadGuildsArgs : global::ProtoBuf.IExtensible
  {
    public LoadGuildsArgs() {}
    

    private int _Pages = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Pages", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pages
    {
      get { return _Pages; }
      set { _Pages = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.GuildBriefArgs> _Guild = new global::System.Collections.Generic.List<Action.Model.GuildBriefArgs>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Guild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.GuildBriefArgs> Guild
    {
      get { return _Guild; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildBriefArgs")]
  public partial class GuildBriefArgs : global::ProtoBuf.IExtensible
  {
    public GuildBriefArgs() {}
    

    private string _GuildName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"GuildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GuildName
    {
      get { return _GuildName; }
      set { _GuildName = value; }
    }

    private string _Description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Description
    {
      get { return _Description; }
      set { _Description = value; }
    }

    private int _MemberMaxCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"MemberMaxCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MemberMaxCount
    {
      get { return _MemberMaxCount; }
      set { _MemberMaxCount = value; }
    }

    private int _MemberCount = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MemberCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MemberCount
    {
      get { return _MemberCount; }
      set { _MemberCount = value; }
    }

    private string _LeaderName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"LeaderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string LeaderName
    {
      get { return _LeaderName; }
      set { _LeaderName = value; }
    }

    private int _GuildLevel = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"GuildLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GuildLevel
    {
      get { return _GuildLevel; }
      set { _GuildLevel = value; }
    }

    private int _LeaderVip = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"LeaderVip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LeaderVip
    {
      get { return _LeaderVip; }
      set { _LeaderVip = value; }
    }

    private bool _IfApply = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"IfApply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfApply
    {
      get { return _IfApply; }
      set { _IfApply = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeGuildPostArgs")]
  public partial class ChangeGuildPostArgs : global::ProtoBuf.IExtensible
  {
    public ChangeGuildPostArgs() {}
    

    private string _MemberName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MemberName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string MemberName
    {
      get { return _MemberName; }
      set { _MemberName = value; }
    }

    private Action.Model.PostType _ToPost = Action.Model.PostType.Common;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ToPost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.PostType.Common)]
    public Action.Model.PostType ToPost
    {
      get { return _ToPost; }
      set { _ToPost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildLogArgs")]
  public partial class GuildLogArgs : global::ProtoBuf.IExtensible
  {
    public GuildLogArgs() {}
    

    private int _Time = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Time
    {
      get { return _Time; }
      set { _Time = value; }
    }

    private string _Player = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Player
    {
      get { return _Player; }
      set { _Player = value; }
    }

    private Action.Model.GuildLogType _Type = Action.Model.GuildLogType.Join;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.GuildLogType.Join)]
    public Action.Model.GuildLogType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Args = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Args", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Args
    {
      get { return _Args; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyPlayerArgs")]
  public partial class ApplyPlayerArgs : global::ProtoBuf.IExtensible
  {
    public ApplyPlayerArgs() {}
    

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private int _Viplevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Viplevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Viplevel
    {
      get { return _Viplevel; }
      set { _Viplevel = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyListArgs")]
  public partial class ApplyListArgs : global::ProtoBuf.IExtensible
  {
    public ApplyListArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.ApplyPlayerArgs> _Players = new global::System.Collections.Generic.List<Action.Model.ApplyPlayerArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.ApplyPlayerArgs> Players
    {
      get { return _Players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildLogListArgs")]
  public partial class GuildLogListArgs : global::ProtoBuf.IExtensible
  {
    public GuildLogListArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.GuildLogArgs> _Logs = new global::System.Collections.Generic.List<Action.Model.GuildLogArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Logs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.GuildLogArgs> Logs
    {
      get { return _Logs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AgreeJoinArgs")]
  public partial class AgreeJoinArgs : global::ProtoBuf.IExtensible
  {
    public AgreeJoinArgs() {}
    

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }

    private bool _IfAgree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IfAgree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfAgree
    {
      get { return _IfAgree; }
      set { _IfAgree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PostType")]
    public enum PostType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Common", Value=0)]
      Common = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Deputy", Value=1)]
      Deputy = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Leader", Value=2)]
      Leader = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GuildLogType")]
    public enum GuildLogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Join", Value=1)]
      Join = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Leave", Value=2)]
      Leave = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Transfer", Value=3)]
      Transfer = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Post", Value=4)]
      Post = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Contribute", Value=5)]
      Contribute = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LevelUp", Value=6)]
      LevelUp = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Impeach", Value=7)]
      Impeach = 7
    }
  
}