//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_HeroArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
// Note: requires additional types generated from: protos/CommonArgs.proto
// Note: requires additional types generated from: protos/_EquipArgs.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadHerosArgs")]
  public partial class LoadHerosArgs : global::ProtoBuf.IExtensible
  {
    public LoadHerosArgs() {}
    

    private string _Player = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Player
    {
      get { return _Player; }
      set { _Player = value; }
    }

    private int _Sex = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.Hero1Args> _Heros = new global::System.Collections.Generic.List<Action.Model.Hero1Args>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Heros", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.Hero1Args> Heros
    {
      get { return _Heros; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hero1Args")]
  public partial class Hero1Args : global::ProtoBuf.IExtensible
  {
    public Hero1Args() {}
    

    private Action.Model.ObjArgs _Obj = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.ObjArgs Obj
    {
      get { return _Obj; }
      set { _Obj = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hero2Args")]
  public partial class Hero2Args : global::ProtoBuf.IExtensible
  {
    public Hero2Args() {}
    

    private Action.Model.ObjArgs _Obj = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.ObjArgs Obj
    {
      get { return _Obj; }
      set { _Obj = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _HP = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.Equip2Args> _Equips = new global::System.Collections.Generic.List<Action.Model.Equip2Args>();
    [global::ProtoBuf.ProtoMember(5, Name=@"Equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.Equip2Args> Equips
    {
      get { return _Equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hero3Args")]
  public partial class Hero3Args : global::ProtoBuf.IExtensible
  {
    public Hero3Args() {}
    

    private Action.Model.ObjArgs _Obj = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.ObjArgs Obj
    {
      get { return _Obj; }
      set { _Obj = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _Exp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }

    private int _HP = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }

    private int _CommonAttack = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"CommonAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CommonAttack
    {
      get { return _CommonAttack; }
      set { _CommonAttack = value; }
    }

    private int _CommonDefence = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"CommonDefence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CommonDefence
    {
      get { return _CommonDefence; }
      set { _CommonDefence = value; }
    }

    private int _SkillAttack = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"SkillAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillAttack
    {
      get { return _SkillAttack; }
      set { _SkillAttack = value; }
    }

    private int _SkillDefence = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"SkillDefence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillDefence
    {
      get { return _SkillDefence; }
      set { _SkillDefence = value; }
    }

    private int _FirstStrike = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"FirstStrike", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int FirstStrike
    {
      get { return _FirstStrike; }
      set { _FirstStrike = value; }
    }

    private int _Hit = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"Hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Hit
    {
      get { return _Hit; }
      set { _Hit = value; }
    }

    private int _Dodge = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"Dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Dodge
    {
      get { return _Dodge; }
      set { _Dodge = value; }
    }

    private int _Crack = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"Crack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Crack
    {
      get { return _Crack; }
      set { _Crack = value; }
    }

    private int _Block = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"Block", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Block
    {
      get { return _Block; }
      set { _Block = value; }
    }

    private int _Crit = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Crit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Crit
    {
      get { return _Crit; }
      set { _Crit = value; }
    }

    private int _Tenacity = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Tenacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Tenacity
    {
      get { return _Tenacity; }
      set { _Tenacity = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.Equip2Args> _Equips = new global::System.Collections.Generic.List<Action.Model.Equip2Args>();
    [global::ProtoBuf.ProtoMember(17, Name=@"Equips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.Equip2Args> Equips
    {
      get { return _Equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RefreshLevelArgs")]
  public partial class RefreshLevelArgs : global::ProtoBuf.IExtensible
  {
    public RefreshLevelArgs() {}
    

    private int _HeroLevel = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroLevel
    {
      get { return _HeroLevel; }
      set { _HeroLevel = value; }
    }

    private int _HeroExp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"HeroExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroExp
    {
      get { return _HeroExp; }
      set { _HeroExp = value; }
    }

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroPosArgs")]
  public partial class HeroPosArgs : global::ProtoBuf.IExtensible
  {
    public HeroPosArgs() {}
    

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }

    private int _TargetPos = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TargetPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TargetPos
    {
      get { return _TargetPos; }
      set { _TargetPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroShopArgs")]
  public partial class HeroShopArgs : global::ProtoBuf.IExtensible
  {
    public HeroShopArgs() {}
    

    private int _HeroSettingId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroSettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroSettingId
    {
      get { return _HeroSettingId; }
      set { _HeroSettingId = value; }
    }

    private bool _IfPossess = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"IfPossess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfPossess
    {
      get { return _IfPossess; }
      set { _IfPossess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadHeroShopArgs")]
  public partial class LoadHeroShopArgs : global::ProtoBuf.IExtensible
  {
    public LoadHeroShopArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.HeroShopArgs> _LoadHeroShop = new global::System.Collections.Generic.List<Action.Model.HeroShopArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LoadHeroShop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.HeroShopArgs> LoadHeroShop
    {
      get { return _LoadHeroShop; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadEmbattleArgs")]
  public partial class LoadEmbattleArgs : global::ProtoBuf.IExtensible
  {
    public LoadEmbattleArgs() {}
    
    private readonly global::System.Collections.Generic.List<int> _Pos = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Pos
    {
      get { return _Pos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpDownQueueArgs")]
  public partial class UpDownQueueArgs : global::ProtoBuf.IExtensible
  {
    public UpDownQueueArgs() {}
    

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }

    private int _Flag = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}