//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_HomeArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateBuildingArgs")]
  public partial class CreateBuildingArgs : global::ProtoBuf.IExtensible
  {
    public CreateBuildingArgs() {}
    

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _X = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int X
    {
      get { return _X; }
      set { _X = value; }
    }

    private int _Y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadHomeArgs")]
  public partial class LoadHomeArgs : global::ProtoBuf.IExtensible
  {
    public LoadHomeArgs() {}
    

    private string _Name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Properties = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Properties", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Properties
    {
      get { return _Properties; }
    }
  
    private readonly global::System.Collections.Generic.List<Action.Model.BuildingArgs> _BuildArgsCollection = new global::System.Collections.Generic.List<Action.Model.BuildingArgs>();
    [global::ProtoBuf.ProtoMember(3, Name=@"BuildArgsCollection", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.BuildingArgs> BuildArgsCollection
    {
      get { return _BuildArgsCollection; }
    }
  

    private int _MinX = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MinX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MinX
    {
      get { return _MinX; }
      set { _MinX = value; }
    }

    private int _MinY = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MinY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MinY
    {
      get { return _MinY; }
      set { _MinY = value; }
    }

    private int _MaxX = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MaxX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxX
    {
      get { return _MaxX; }
      set { _MaxX = value; }
    }

    private int _MaxY = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"MaxY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxY
    {
      get { return _MaxY; }
      set { _MaxY = value; }
    }

    private int _HomeLevel = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"HomeLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HomeLevel
    {
      get { return _HomeLevel; }
      set { _HomeLevel = value; }
    }

    private int _PlayerSex = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"PlayerSex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PlayerSex
    {
      get { return _PlayerSex; }
      set { _PlayerSex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildingArgs")]
  public partial class BuildingArgs : global::ProtoBuf.IExtensible
  {
    public BuildingArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _X = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int X
    {
      get { return _X; }
      set { _X = value; }
    }

    private int _Y = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Y
    {
      get { return _Y; }
      set { _Y = value; }
    }

    private int _TimeRest = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"TimeRest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TimeRest
    {
      get { return _TimeRest; }
      set { _TimeRest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateReturnArgs")]
  public partial class CreateReturnArgs : global::ProtoBuf.IExtensible
  {
    public CreateReturnArgs() {}
    

    private Action.Model.BuildingArgs _Building = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Building", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.BuildingArgs Building
    {
      get { return _Building; }
      set { _Building = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.MaterialsArgs> _Materials = new global::System.Collections.Generic.List<Action.Model.MaterialsArgs>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.MaterialsArgs> Materials
    {
      get { return _Materials; }
    }
  

    private int _Money = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveBuildingArgs")]
  public partial class MoveBuildingArgs : global::ProtoBuf.IExtensible
  {
    public MoveBuildingArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _X = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int X
    {
      get { return _X; }
      set { _X = value; }
    }

    private int _Y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoveBuildingSuccessArgs")]
  public partial class MoveBuildingSuccessArgs : global::ProtoBuf.IExtensible
  {
    public MoveBuildingSuccessArgs() {}
    

    private Action.Model.MoveBuildingArgs _Building = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Building", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.MoveBuildingArgs Building
    {
      get { return _Building; }
      set { _Building = value; }
    }

    private int _Money = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarvestSuccessArgs")]
  public partial class HarvestSuccessArgs : global::ProtoBuf.IExtensible
  {
    public HarvestSuccessArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _TimeRest = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TimeRest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TimeRest
    {
      get { return _TimeRest; }
      set { _TimeRest = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpgradeSuccessArgs")]
  public partial class UpgradeSuccessArgs : global::ProtoBuf.IExtensible
  {
    public UpgradeSuccessArgs() {}
    

    private int _HomeLevel = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"HomeLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HomeLevel
    {
      get { return _HomeLevel; }
      set { _HomeLevel = value; }
    }

    private int _MinX = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"MinX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MinX
    {
      get { return _MinX; }
      set { _MinX = value; }
    }

    private int _MinY = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"MinY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MinY
    {
      get { return _MinY; }
      set { _MinY = value; }
    }

    private int _MaxX = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"MaxX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxX
    {
      get { return _MaxX; }
      set { _MaxX = value; }
    }

    private int _MaxY = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MaxY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MaxY
    {
      get { return _MaxY; }
      set { _MaxY = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DelBuildingArgs")]
  public partial class DelBuildingArgs : global::ProtoBuf.IExtensible
  {
    public DelBuildingArgs() {}
    

    private int _BuildingId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"BuildingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BuildingId
    {
      get { return _BuildingId; }
      set { _BuildingId = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.MaterialsArgs> _Materials = new global::System.Collections.Generic.List<Action.Model.MaterialsArgs>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Materials", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.MaterialsArgs> Materials
    {
      get { return _Materials; }
    }
  

    private int _Money = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaterialsArgs")]
  public partial class MaterialsArgs : global::ProtoBuf.IExtensible
  {
    public MaterialsArgs() {}
    

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Count = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Count
    {
      get { return _Count; }
      set { _Count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertiesArgs")]
  public partial class PropertiesArgs : global::ProtoBuf.IExtensible
  {
    public PropertiesArgs() {}
    
    private readonly global::System.Collections.Generic.List<int> _Properties = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Properties", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Properties
    {
      get { return _Properties; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}