//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_HuntArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulArgs")]
  public partial class SoulArgs : global::ProtoBuf.IExtensible
  {
    public SoulArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _Exp = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TempSoulArgs")]
  public partial class TempSoulArgs : global::ProtoBuf.IExtensible
  {
    public TempSoulArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadHunthouseArgs")]
  public partial class LoadHunthouseArgs : global::ProtoBuf.IExtensible
  {
    public LoadHunthouseArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.TempSoulArgs> _TempSouls = new global::System.Collections.Generic.List<Action.Model.TempSoulArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"TempSouls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.TempSoulArgs> TempSouls
    {
      get { return _TempSouls; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _LightSoulQualities = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"LightSoulQualities", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> LightSoulQualities
    {
      get { return _LightSoulQualities; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwallowSoulArgs")]
  public partial class SwallowSoulArgs : global::ProtoBuf.IExtensible
  {
    public SwallowSoulArgs() {}
    

    private int _Soul1 = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Soul1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Soul1
    {
      get { return _Soul1; }
      set { _Soul1 = value; }
    }

    private int _Soul2 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Soul2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Soul2
    {
      get { return _Soul2; }
      set { _Soul2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PickupSoulsArgs")]
  public partial class PickupSoulsArgs : global::ProtoBuf.IExtensible
  {
    public PickupSoulsArgs() {}
    

    private bool _IfFull = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"IfFull", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IfFull
    {
      get { return _IfFull; }
      set { _IfFull = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.TempSoulArgs> _TempSouls = new global::System.Collections.Generic.List<Action.Model.TempSoulArgs>();
    [global::ProtoBuf.ProtoMember(2, Name=@"TempSouls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.TempSoulArgs> TempSouls
    {
      get { return _TempSouls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HuntSoulArgs")]
  public partial class HuntSoulArgs : global::ProtoBuf.IExtensible
  {
    public HuntSoulArgs() {}
    
    private readonly global::System.Collections.Generic.List<int> _LightSoulQualities = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"LightSoulQualities", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> LightSoulQualities
    {
      get { return _LightSoulQualities; }
    }
  

    private Action.Model.TempSoulArgs _TempSoul = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"TempSoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.TempSoulArgs TempSoul
    {
      get { return _TempSoul; }
      set { _TempSoul = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WearSoulArgs")]
  public partial class WearSoulArgs : global::ProtoBuf.IExtensible
  {
    public WearSoulArgs() {}
    

    private int _SoulId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"SoulId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoulId
    {
      get { return _SoulId; }
      set { _SoulId = value; }
    }

    private int _HeroId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"HeroId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HeroId
    {
      get { return _HeroId; }
      set { _HeroId = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnwearSoulArgs")]
  public partial class UnwearSoulArgs : global::ProtoBuf.IExtensible
  {
    public UnwearSoulArgs() {}
    

    private Action.Model.WearSoulArgs _WearSoul = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"WearSoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.WearSoulArgs WearSoul
    {
      get { return _WearSoul; }
      set { _WearSoul = value; }
    }

    private Action.Model.SoulArgs _UnwearSoul = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UnwearSoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Action.Model.SoulArgs UnwearSoul
    {
      get { return _UnwearSoul; }
      set { _UnwearSoul = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwallowSuccessArgs")]
  public partial class SwallowSuccessArgs : global::ProtoBuf.IExtensible
  {
    public SwallowSuccessArgs() {}
    

    private int _BeSwallowSoulId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"BeSwallowSoulId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BeSwallowSoulId
    {
      get { return _BeSwallowSoulId; }
      set { _BeSwallowSoulId = value; }
    }

    private int _SoulId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SoulId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoulId
    {
      get { return _SoulId; }
      set { _SoulId = value; }
    }

    private int _SoulLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"SoulLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoulLevel
    {
      get { return _SoulLevel; }
      set { _SoulLevel = value; }
    }

    private int _SoulExp = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SoulExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SoulExp
    {
      get { return _SoulExp; }
      set { _SoulExp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SoulsArgs")]
  public partial class SoulsArgs : global::ProtoBuf.IExtensible
  {
    public SoulsArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.SoulArgs> _Souls = new global::System.Collections.Generic.List<Action.Model.SoulArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Souls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.SoulArgs> Souls
    {
      get { return _Souls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TempSoulsArgs")]
  public partial class TempSoulsArgs : global::ProtoBuf.IExtensible
  {
    public TempSoulsArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.TempSoulArgs> _TempSoul = new global::System.Collections.Generic.List<Action.Model.TempSoulArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"TempSoul", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.TempSoulArgs> TempSoul
    {
      get { return _TempSoul; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HuntSoulsArgs")]
  public partial class HuntSoulsArgs : global::ProtoBuf.IExtensible
  {
    public HuntSoulsArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.HuntSoulArgs> _HuntSouls = new global::System.Collections.Generic.List<Action.Model.HuntSoulArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"HuntSouls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.HuntSoulArgs> HuntSouls
    {
      get { return _HuntSouls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeroHuntArgs")]
  public partial class HeroHuntArgs : global::ProtoBuf.IExtensible
  {
    public HeroHuntArgs() {}
    
    private readonly global::System.Collections.Generic.List<int> _OpenPos = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"OpenPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> OpenPos
    {
      get { return _OpenPos; }
    }
  
    private readonly global::System.Collections.Generic.List<Action.Model.SoulArgs> _Souls = new global::System.Collections.Generic.List<Action.Model.SoulArgs>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Souls", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.SoulArgs> Souls
    {
      get { return _Souls; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}