//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_PrizeArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
// Note: requires additional types generated from: protos/CommonArgs.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrizeArrayArgs")]
  public partial class PrizeArrayArgs : global::ProtoBuf.IExtensible
  {
    public PrizeArrayArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.PrizeArgs> _Prizes = new global::System.Collections.Generic.List<Action.Model.PrizeArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Prizes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.PrizeArgs> Prizes
    {
      get { return _Prizes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrizeArgs")]
  public partial class PrizeArgs : global::ProtoBuf.IExtensible
  {
    public PrizeArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private string _Title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Title
    {
      get { return _Title; }
      set { _Title = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrizeTipArray")]
  public partial class PrizeTipArray : global::ProtoBuf.IExtensible
  {
    public PrizeTipArray() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.PrizeTip> _Tips = new global::System.Collections.Generic.List<Action.Model.PrizeTip>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Tips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.PrizeTip> Tips
    {
      get { return _Tips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PrizeTip")]
  public partial class PrizeTip : global::ProtoBuf.IExtensible
  {
    public PrizeTip() {}
    

    private int _Gold = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Gold
    {
      get { return _Gold; }
      set { _Gold = value; }
    }

    private int _Money = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }

    private int _Energy = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Energy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Energy
    {
      get { return _Energy; }
      set { _Energy = value; }
    }

    private int _Repute = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Repute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Repute
    {
      get { return _Repute; }
      set { _Repute = value; }
    }

    private int _Exp = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.IdCountArgs> _Items = new global::System.Collections.Generic.List<Action.Model.IdCountArgs>();
    [global::ProtoBuf.ProtoMember(8, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.IdCountArgs> Items
    {
      get { return _Items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}