//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_ShopArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopGoodsArgs")]
  public partial class ShopGoodsArgs : global::ProtoBuf.IExtensible
  {
    public ShopGoodsArgs() {}
    

    private int _GoodsClass = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"GoodsClass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoodsClass
    {
      get { return _GoodsClass; }
      set { _GoodsClass = value; }
    }

    private int _ItemId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }

    private int _ItemCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ItemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ItemCount
    {
      get { return _ItemCount; }
      set { _ItemCount = value; }
    }

    private int _OldPrice = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"OldPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int OldPrice
    {
      get { return _OldPrice; }
      set { _OldPrice = value; }
    }

    private int _NewPrice = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"NewPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NewPrice
    {
      get { return _NewPrice; }
      set { _NewPrice = value; }
    }

    private bool _IsNew = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"IsNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsNew
    {
      get { return _IsNew; }
      set { _IsNew = value; }
    }

    private bool _IsDiscount = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"IsDiscount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsDiscount
    {
      get { return _IsDiscount; }
      set { _IsDiscount = value; }
    }

    private int _GoodsId = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"GoodsId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int GoodsId
    {
      get { return _GoodsId; }
      set { _GoodsId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoadShopArgs")]
  public partial class LoadShopArgs : global::ProtoBuf.IExtensible
  {
    public LoadShopArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.ShopGoodsArgs> _Goods = new global::System.Collections.Generic.List<Action.Model.ShopGoodsArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Goods", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.ShopGoodsArgs> Goods
    {
      get { return _Goods; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}