//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/_TaskArgs.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskArrayArgs")]
  public partial class TaskArrayArgs : global::ProtoBuf.IExtensible
  {
    public TaskArrayArgs() {}
    
    private readonly global::System.Collections.Generic.List<Action.Model.TaskArgs> _Tasks = new global::System.Collections.Generic.List<Action.Model.TaskArgs>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Tasks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.TaskArgs> Tasks
    {
      get { return _Tasks; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskArgs")]
  public partial class TaskArgs : global::ProtoBuf.IExtensible
  {
    public TaskArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _Progress = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Progress
    {
      get { return _Progress; }
      set { _Progress = value; }
    }

    private Action.Model.TaskStatus _Status = Action.Model.TaskStatus.Locked;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.TaskStatus.Locked)]
    public Action.Model.TaskStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RandomTaskArgs")]
  public partial class RandomTaskArgs : global::ProtoBuf.IExtensible
  {
    public RandomTaskArgs() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _Progress = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Progress
    {
      get { return _Progress; }
      set { _Progress = value; }
    }

    private Action.Model.TaskStatus _Status = Action.Model.TaskStatus.Locked;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.TaskStatus.Locked)]
    public Action.Model.TaskStatus Status
    {
      get { return _Status; }
      set { _Status = value; }
    }

    private int _Index = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Index
    {
      get { return _Index; }
      set { _Index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TaskStatus")]
    public enum TaskStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Locked", Value=0)]
      Locked = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Opened", Value=1)]
      Opened = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Doing", Value=2)]
      Doing = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Finished", Value=3)]
      Finished = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Closed", Value=4)]
      Closed = 4
    }
  
}