//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protos/BattleReport.proto
// Note: requires additional types generated from: protobuf-net.proto
namespace Action.Model
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleReport")]
  public partial class BattleReport : global::ProtoBuf.IExtensible
  {
    public BattleReport() {}
    

    private string _Guid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Guid
    {
      get { return _Guid; }
      set { _Guid = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.BattleUnit> _Units = new global::System.Collections.Generic.List<Action.Model.BattleUnit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.BattleUnit> Units
    {
      get { return _Units; }
    }
  
    private readonly global::System.Collections.Generic.List<Action.Model.BattleRound> _Rounds = new global::System.Collections.Generic.List<Action.Model.BattleRound>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Rounds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.BattleRound> Rounds
    {
      get { return _Rounds; }
    }
  

    private string _Side1 = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Side1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Side1
    {
      get { return _Side1; }
      set { _Side1 = value; }
    }

    private string _Side2 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Side2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Side2
    {
      get { return _Side2; }
      set { _Side2 = value; }
    }

    private bool _Win = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Win
    {
      get { return _Win; }
      set { _Win = value; }
    }

    private int _Sex1 = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Sex1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Sex1
    {
      get { return _Sex1; }
      set { _Sex1 = value; }
    }

    private int _Sex2 = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Sex2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Sex2
    {
      get { return _Sex2; }
      set { _Sex2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleUnit")]
  public partial class BattleUnit : global::ProtoBuf.IExtensible
  {
    public BattleUnit() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }

    private int _SettingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SettingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SettingId
    {
      get { return _SettingId; }
      set { _SettingId = value; }
    }

    private int _Level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Level
    {
      get { return _Level; }
      set { _Level = value; }
    }

    private int _SkillId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }

    private int _Pos = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Pos
    {
      get { return _Pos; }
      set { _Pos = value; }
    }

    private int _HP = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int HP
    {
      get { return _HP; }
      set { _HP = value; }
    }

    private int _XP = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"XP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int XP
    {
      get { return _XP; }
      set { _XP = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleRound")]
  public partial class BattleRound : global::ProtoBuf.IExtensible
  {
    public BattleRound() {}
    

    private int _Id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Id
    {
      get { return _Id; }
      set { _Id = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.BattleAction> _Actions = new global::System.Collections.Generic.List<Action.Model.BattleAction>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Actions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.BattleAction> Actions
    {
      get { return _Actions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleAction")]
  public partial class BattleAction : global::ProtoBuf.IExtensible
  {
    public BattleAction() {}
    

    private int _UnitId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UnitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int UnitId
    {
      get { return _UnitId; }
      set { _UnitId = value; }
    }

    private int _SkillId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int SkillId
    {
      get { return _SkillId; }
      set { _SkillId = value; }
    }
    private readonly global::System.Collections.Generic.List<Action.Model.BattleEffect> _Effects = new global::System.Collections.Generic.List<Action.Model.BattleEffect>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Effects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Action.Model.BattleEffect> Effects
    {
      get { return _Effects; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleEffect")]
  public partial class BattleEffect : global::ProtoBuf.IExtensible
  {
    public BattleEffect() {}
    

    private int _UnitId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UnitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int UnitId
    {
      get { return _UnitId; }
      set { _UnitId = value; }
    }

    private Action.Model.BattleEffectType _Type = Action.Model.BattleEffectType.Common;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Action.Model.BattleEffectType.Common)]
    public Action.Model.BattleEffectType Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private int _Data = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BattleEffectType")]
    public enum BattleEffectType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Common", Value=0)]
      Common = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dodge", Value=1)]
      Dodge = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Crit", Value=2)]
      Crit = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Poisoning", Value=3)]
      Poisoning = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Cure", Value=4)]
      Cure = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XpUp", Value=5)]
      XpUp = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XpDown", Value=6)]
      XpDown = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XpFull", Value=7)]
      XpFull = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XpClear", Value=8)]
      XpClear = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"XpUpdate", Value=9)]
      XpUpdate = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AttackUp", Value=10)]
      AttackUp = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AttackDown", Value=11)]
      AttackDown = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DefenceUp", Value=12)]
      DefenceUp = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DefenceDown", Value=13)]
      DefenceDown = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HitUp", Value=20)]
      HitUp = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HitDown", Value=21)]
      HitDown = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DodgeUp", Value=22)]
      DodgeUp = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DodgeDown", Value=23)]
      DodgeDown = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CrackUp", Value=24)]
      CrackUp = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CrackDown", Value=25)]
      CrackDown = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockUp", Value=26)]
      BlockUp = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BlockDown", Value=27)]
      BlockDown = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CritUp", Value=28)]
      CritUp = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CritDown", Value=29)]
      CritDown = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TenacityUp", Value=30)]
      TenacityUp = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TenacityDown", Value=31)]
      TenacityDown = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusNormal", Value=40)]
      StatusNormal = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusVertigo", Value=41)]
      StatusVertigo = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusSleep", Value=42)]
      StatusSleep = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusPoisoning", Value=43)]
      StatusPoisoning = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"StatusLock", Value=44)]
      StatusLock = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DoubleHit", Value=50)]
      DoubleHit = 50
    }
  
}